"""Continuous Learning Loop Service (Phase 10.1).

Closes the feedback loop: every cybersecurity activity becomes training data.
Recon → Scan → Finding → Analysis → Pattern → Graph → Memory → TTP → Playbook → Improvement.

Orchestrates post-activity learning across all knowledge subsystems without
direct coupling — communicates through structured events.
"""

import json
import logging
import time
from typing import Any

from hydra.services.base import BaseService

logger = logging.getLogger("hydra.services.learning_loop")

ACTIVITY_TYPES = (
    "recon", "scan", "finding", "analysis", "extraction",
    "verification", "exploitation", "report", "ingestion",
    "manual_note", "campaign_step",
)

LEARNING_STAGES = (
    "capture", "extract", "correlate", "update_graph",
    "update_memory", "update_ttp", "update_playbook",
    "update_confidence", "recommend",
)


class LearningEvent:
    __slots__ = (
        "id", "activity_type", "timestamp", "target", "input_data",
        "output_data", "stages_completed", "lessons", "improvements",
    )

    def __init__(self, activity_type: str, target: str = "",
                 input_data: dict | None = None,
                 output_data: dict | None = None):
        self.id = f"le-{int(time.time() * 1000)}"
        self.activity_type = activity_type
        self.timestamp = time.time()
        self.target = target
        self.input_data = input_data or {}
        self.output_data = output_data or {}
        self.stages_completed: list[str] = []
        self.lessons: list[dict] = []
        self.improvements: list[dict] = []

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "activity_type": self.activity_type,
            "timestamp": self.timestamp,
            "target": self.target,
            "stages_completed": self.stages_completed,
            "lesson_count": len(self.lessons),
            "improvement_count": len(self.improvements),
        }


class LearningLoopService(BaseService):
    """Continuous learning loop — every activity improves future performance."""

    def __init__(self, event_bus, data_dir=None):
        super().__init__(event_bus, data_dir)
        self._log_path = self._data_dir / "learning_loop.jsonl"

    def process_activity(self, activity_type: str, target: str = "",
                         input_data: dict | None = None,
                         output_data: dict | None = None) -> dict:
        """Process a completed activity through the full learning pipeline."""
        if activity_type not in ACTIVITY_TYPES:
            return {"status": "error", "error": f"Unknown activity: {activity_type}"}

        event = LearningEvent(activity_type, target, input_data, output_data)

        event.stages_completed.append("capture")
        lessons = self._extract_lessons(event)
        event.lessons = lessons
        event.stages_completed.append("extract")

        correlations = self._correlate(event)
        event.stages_completed.append("correlate")

        self._update_graph(event)
        event.stages_completed.append("update_graph")

        self._update_memory(event)
        event.stages_completed.append("update_memory")

        if event.activity_type in ("finding", "scan", "exploitation"):
            self._update_ttp(event)
            event.stages_completed.append("update_ttp")

        improvements = self._generate_improvements(event)
        event.improvements = improvements
        event.stages_completed.append("recommend")

        self._persist(event)

        self._emit("learning_loop.completed", {
            "event_id": event.id,
            "activity_type": activity_type,
            "target": target,
            "stages": len(event.stages_completed),
            "lessons": len(lessons),
            "improvements": len(improvements),
        })

        return {
            "status": "processed",
            **event.to_dict(),
            "lessons": lessons,
            "improvements": improvements,
            "correlations": correlations,
        }

    def get_recent(self, limit: int = 20) -> list[dict]:
        """Get recent learning events."""
        events = []
        if self._log_path.exists():
            lines = self._log_path.read_text().strip().split("\n")
            for line in lines[-limit:]:
                try:
                    events.append(json.loads(line))
                except (json.JSONDecodeError, Exception):
                    pass
        return events

    def get_improvement_queue(self, limit: int = 10) -> list[dict]:
        """Get pending improvements generated by the learning loop."""
        events = self.get_recent(limit=100)
        queue = []
        for e in events:
            for imp in e.get("improvements", []):
                if not imp.get("applied", False):
                    queue.append(imp)
                    if len(queue) >= limit:
                        return queue
        return queue

    def get_stats(self) -> dict[str, Any]:
        """Learning loop statistics."""
        events = self.get_recent(limit=1000)
        by_type: dict[str, int] = {}
        total_lessons = 0
        total_improvements = 0
        for e in events:
            at = e.get("activity_type", "unknown")
            by_type[at] = by_type.get(at, 0) + 1
            total_lessons += e.get("lesson_count", 0)
            total_improvements += e.get("improvement_count", 0)
        return {
            "total_events": len(events),
            "by_activity_type": by_type,
            "total_lessons": total_lessons,
            "total_improvements": total_improvements,
            "activity_types": list(ACTIVITY_TYPES),
            "stages": list(LEARNING_STAGES),
        }

    def _extract_lessons(self, event: LearningEvent) -> list[dict]:
        """Extract reusable lessons from the activity."""
        lessons = []
        output = event.output_data

        if event.activity_type == "finding":
            vuln_class = output.get("vuln_class", "")
            if vuln_class:
                lessons.append({
                    "type": "technique",
                    "content": f"Discovered {vuln_class} on {event.target}",
                    "vuln_class": vuln_class,
                    "target": event.target,
                })

        if event.activity_type == "scan":
            findings_count = output.get("findings_count", 0)
            tool = output.get("tool", "")
            if tool:
                lessons.append({
                    "type": "tool_effectiveness",
                    "content": f"{tool} produced {findings_count} findings on {event.target}",
                    "tool": tool,
                    "findings_count": findings_count,
                })

        if event.activity_type == "recon":
            assets = output.get("assets_discovered", 0)
            if assets:
                lessons.append({
                    "type": "recon_yield",
                    "content": f"Recon on {event.target} discovered {assets} assets",
                    "assets": assets,
                })

        if event.activity_type == "verification":
            outcome = output.get("outcome", "")
            lessons.append({
                "type": "verification_outcome",
                "content": f"Verification {outcome} for {event.target}",
                "outcome": outcome,
            })

        return lessons

    def _correlate(self, event: LearningEvent) -> list[dict]:
        """Find correlations with existing knowledge."""
        correlations = []
        try:
            from hydra.knowledge.wiki_store import WikiStore
            store = WikiStore(self._data_dir / "wiki")
            target = event.target
            if target:
                hits = store.search(target, limit=5)
                for h in hits:
                    slug = h.get("slug", "") if isinstance(h, dict) else str(h)
                    if slug:
                        correlations.append({
                            "type": "existing_knowledge",
                            "slug": slug,
                            "relation": "same_target",
                        })
        except (ImportError, Exception):
            pass
        return correlations

    def _update_graph(self, event: LearningEvent) -> None:
        """Update knowledge graph with new relationships."""
        self._emit("learning_loop.graph_update", {
            "event_id": event.id,
            "target": event.target,
            "activity_type": event.activity_type,
        })

    def _update_memory(self, event: LearningEvent) -> None:
        """Record activity in cyber memory."""
        self._emit("learning_loop.memory_update", {
            "event_id": event.id,
            "target": event.target,
            "lessons": len(event.lessons),
        })

    def _update_ttp(self, event: LearningEvent) -> None:
        """Update TTP mappings from findings."""
        self._emit("learning_loop.ttp_update", {
            "event_id": event.id,
            "activity_type": event.activity_type,
        })

    def _generate_improvements(self, event: LearningEvent) -> list[dict]:
        """Generate improvement suggestions from the activity."""
        improvements = []
        if event.activity_type == "scan" and event.output_data.get("findings_count", 0) == 0:
            improvements.append({
                "type": "tool_selection",
                "suggestion": f"Consider alternative tools for {event.target}",
                "priority": "low",
                "applied": False,
            })
        if event.activity_type == "finding":
            improvements.append({
                "type": "pattern_candidate",
                "suggestion": f"Check if {event.output_data.get('vuln_class', 'finding')} pattern exists",
                "priority": "medium",
                "applied": False,
            })
        return improvements

    def _persist(self, event: LearningEvent) -> None:
        """Append learning event to the log."""
        self._log_path.parent.mkdir(parents=True, exist_ok=True)
        record = {
            **event.to_dict(),
            "lessons": event.lessons,
            "improvements": event.improvements,
        }
        with open(self._log_path, "a") as f:
            f.write(json.dumps(record) + "\n")
